/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;
import java.awt.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import loginform.login;

/**
 *
 * @author Admin
 */
public class ajout_inst extends javax.swing.JFrame {
       public String s;
    /**
     * Creates new form Home
     */
    public ajout_inst() {
        initComponents();
        
      
        clock();
        listeaccee.setVisible(false );
        afficher_cours();
    }
    public void afficher_cours(){
        Connection conn=connexionBD.Conexion();
        String sql="select nom_mat from cours";
         try {
        cours.removeAllItems();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet result = ps.executeQuery();
           System.out.println("--> SQLException bien vf : "+ result ) ;
            while (result.next()) {
                cours.addItem(result.getString(1));
            }
           
       } catch (SQLException ex) {
        //Logger.getLogger(instititeur.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("--> SQLException : " + ex) ;
       
    }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnclock = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtinscri = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        listeaccee = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nom_pren = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        num = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datenaiss = new com.toedter.calendar.JDateChooser();
        etat_inst = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cours = new javax.swing.JComboBox<>();
        cin = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        labimg = new javax.swing.JLabel();
        btnpath1 = new javax.swing.JButton();
        action = new javax.swing.JPanel();
        btnaj = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.setAlignmentY(0.0F);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        btnclock.setBackground(new java.awt.Color(153, 204, 255));
        btnclock.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnclock.setText("jButton1");
        btnclock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclockActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add a teacher ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(149, 149, 149)
                .addComponent(btnclock, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclock, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 70));

        jPanel3.setBackground(new java.awt.Color(220, 246, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Teacher information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 0, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtinscri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtinscri.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.add(txtinscri, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 333, 140, 24));

        jLabel25.setText("CIN   :            ");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 88, 18));

        listeaccee.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Name :");

        nom_pren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_prenActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero:");

        num.setMaximumSize(new java.awt.Dimension(9999999, 0));
        num.setMinimumSize(new java.awt.Dimension(9999999, 0));

        jLabel7.setText("Mail: ");

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });

        jLabel5.setText("Date of birth:");

        datenaiss.setDateFormatString("yyyy-MM-dd");
        datenaiss.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                datenaissComponentAdded(evt);
            }
        });
        datenaiss.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datenaissAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        datenaiss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                datenaissMouseReleased(evt);
            }
        });
        datenaiss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datenaissKeyReleased(evt);
            }
        });

        etat_inst.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        etat_inst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "single", "married", "divorced", "other" }));

        jLabel23.setText("State");

        jLabel24.setText("course can teach:");

        cours.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        cours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dessin", "musique", "" }));
        cours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listeacceeLayout = new javax.swing.GroupLayout(listeaccee);
        listeaccee.setLayout(listeacceeLayout);
        listeacceeLayout.setHorizontalGroup(
            listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeacceeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom_pren, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datenaiss, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(etat_inst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        listeacceeLayout.setVerticalGroup(
            listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeacceeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_pren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(etat_inst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        jPanel6.add(listeaccee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 230));

        cin.setMaximumSize(new java.awt.Dimension(9999999, 0));
        cin.setMinimumSize(new java.awt.Dimension(9999999, 0));
        cin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cinStateChanged(evt);
            }
        });
        cin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cinFocusLost(evt);
            }
        });
        cin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cinMouseExited(evt);
            }
        });
        jPanel6.add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 290, 320));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Photo instititeur :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labimg, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labimg, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 220, 230));
        jPanel5.getAccessibleContext().setAccessibleName("Teacher picture :");

        btnpath1.setBackground(new java.awt.Color(0, 0, 102));
        btnpath1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpath1.setForeground(new java.awt.Color(255, 255, 255));
        btnpath1.setText("Browse");
        btnpath1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpath1MouseClicked(evt);
            }
        });
        btnpath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpath1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpath1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 120, 40));

        action.setBackground(new java.awt.Color(255, 255, 255));
        action.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0)), "Action :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        btnaj.setBackground(new java.awt.Color(220, 246, 254));
        btnaj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        btnaj.setText("ADD");
        btnaj.setToolTipText("");
        btnaj.setAutoscrolls(true);
        btnaj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnaj.setContentAreaFilled(false);
        btnaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnaj.setOpaque(true);
        btnaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnajMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnajMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnajMousePressed(evt);
            }
        });
        btnaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionLayout = new javax.swing.GroupLayout(action);
        action.setLayout(actionLayout);
        actionLayout.setHorizontalGroup(
            actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        actionLayout.setVerticalGroup(
            actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnaj, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(action, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 150, 80));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1070, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void clock ()
    {
        Calendar cal=new GregorianCalendar();
        int day=cal.get(Calendar.DAY_OF_MONTH);
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        
        int h=cal.get(Calendar.HOUR);
        int m=cal.get(Calendar.MINUTE);
        
        btnclock.setText(  " today is "+day+"/"+month+"/"+year+" : "+h+":"+m);
        
        
    }
    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnclockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclockActionPerformed

    private void nom_prenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_prenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_prenActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void datenaissComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_datenaissComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissComponentAdded

    private void datenaissAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datenaissAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissAncestorAdded

    private void datenaissMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datenaissMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissMouseReleased

    private void datenaissKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datenaissKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissKeyReleased

    private void coursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursActionPerformed

    private void btnpath1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpath1MouseClicked
        // TODO add your handling code here:
        JFileChooser file =new JFileChooser();
        FileNameExtensionFilter filter =new FileNameExtensionFilter("IMAGE","jpg","png","gif");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);

        if (result==JFileChooser.APPROVE_OPTION){
            File selected=file.getSelectedFile();
            String path = selected.getAbsolutePath();
            ImageIcon image= new ImageIcon(path);
            Image img=image.getImage();
            Image newimage=img.getScaledInstance(labimg.getWidth(),  labimg.getWidth(),Image.SCALE_SMOOTH);
            ImageIcon finalimg = new ImageIcon(newimage);
            labimg.setIcon(finalimg);
            s =path;
            JOptionPane.showMessageDialog(null, "image choisit"+s );
        } else
        {
            if (result==JFileChooser.CANCEL_OPTION)
            JOptionPane.showMessageDialog(null, "choisit une image" );

        }
    }//GEN-LAST:event_btnpath1MouseClicked

    private void btnpath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpath1ActionPerformed

    }//GEN-LAST:event_btnpath1ActionPerformed

    private void btnajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseClicked
        String  cin_inst=cin.getValue().toString();
        String nom=nom_pren.getText();
        String num_tlfn= num.getValue().toString();
        String admail=mail.getText();
        String etat =etat_inst.getSelectedItem().toString();
        System.out.println("etat choisit  2"+etat);
        String cour_ensg=cours.getSelectedItem().toString();
        System.out.println("cours choisit  2"+cour_ensg);
        Date d=datenaiss.getDate();
        System.out.println("erreur d'insertion 2"+d);

        SimpleDateFormat dateformat =new SimpleDateFormat("dd/MM/yyyy");
        System.out.println("erreur d'insertion 3 maissa    ");
        String date=dateformat.format(datenaiss.getDate());

        System.out.println("erreur d'insertion 3 maissa    "+date);
        /* LocalDate datef = LocalDate.parse(date);
        System.out.println("erreur d'insertion 3 maissa aa   "+datef);
        //LocalDate datenaiss = LocalDate.parse(date, DateTimeFormatter.ISO_DATE);
        */
        try {
            //Chargement du pilote JDBC pour MYSQL puis creation de la connection
            //DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            // ou bien
            //Connection conn = connexionBD.Conexion();
            InputStream img = new FileInputStream(new File(s));

            String requete= "INSERT INTO `instituteur` (`cin_inst`,`name_inst`,`num_inst`,`mail_inst`,`dtenaiss_inst`,`etat`,`image`,`code_mat`) VALUES (?,?,?,?,?,?,?,?)";

            String sql1="SELECT code_mat FROM cours WHERE nom_mat='"+cour_ensg+"'";
            Connection conn = connexionBD.Conexion();
            //ps.executeUpdate(requete);
            
            
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            ResultSet result = ps1.executeQuery();
            System.out.println("verification    ****");
            

           

            PreparedStatement ps = conn.prepareStatement(requete);
            ps.setString(1,cin_inst);
            ps.setString(2,nom);

            ps.setString(3,num_tlfn);
            ps.setString(4,admail);
            // ps.setString(5, datef);
            ps.setString(5,date);
            ps.setString(6,etat);
            // ps.setString(7,cour_ensg);
            ps.setBlob(7, img);
            result.next();
             System.out.println("succée d'insertionc a verifirer    ****"+result.getInt("code_mat"));
            ps.setInt(8,result.getInt(1));

            //ps.setValue(result.getInt("code_mat"));

            ps.executeUpdate();
            System.out.println("success added");
            JOptionPane.showMessageDialog(null, " successfully added  ");

        }catch(SQLException e) {
            System.out.println("--> SQLException : " + e) ;
            
            JOptionPane.showMessageDialog(null, "error ");

        }    catch (FileNotFoundException ex) {
            //Logger.getLogger(ajout_inst.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erreur d'insertion 2");
        }

    }//GEN-LAST:event_btnajMouseClicked

    private void btnajMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseEntered
        btnaj.setBackground(new java.awt.Color(32,242,4));
    }//GEN-LAST:event_btnajMouseEntered

    private void btnajMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseExited
        btnaj.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_btnajMouseExited

    private void btnajMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMousePressed
        btnaj.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnajMousePressed

    private void btnajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajActionPerformed

    }//GEN-LAST:event_btnajActionPerformed

    private void cinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cinStateChanged
        // TODO add your handling code here:
        Connection conn=connexionBD.Conexion();

        //JOptionPane.showMessageDialog(null, "cin saisit" );
        String  cinI=cin.getValue().toString();
        String sql="select id_inst from instituteur where cin_inst='"+cinI+"'";
        System.out.println("--> valeur100 "+cinI+"     ") ;
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet result = ps.executeQuery();
            System.out.println("--> SQLException bien vf : "+ result ) ;
            if (result.next())
            {
                JOptionPane.showMessageDialog(null, "instituteur deja inscrit " );
                 listeaccee.setVisible(false );

            }
            else
            listeaccee.setVisible(true );

        } catch (SQLException ex) {
            //Logger.getLogger(instititeur.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("--> SQLException : " + ex) ;

        }
    }//GEN-LAST:event_cinStateChanged

    private void cinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cinFocusLost

    private void cinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cinMouseClicked

    private void cinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajout_inst().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action;
    private javax.swing.JButton btnaj;
    private javax.swing.JButton btnclock;
    private javax.swing.JButton btnpath1;
    private javax.swing.JSpinner cin;
    private javax.swing.JComboBox<String> cours;
    private com.toedter.calendar.JDateChooser datenaiss;
    private javax.swing.JComboBox<String> etat_inst;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labimg;
    private javax.swing.JPanel listeaccee;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nom_pren;
    private javax.swing.JSpinner num;
    private javax.swing.JLabel txtinscri;
    // End of variables declaration//GEN-END:variables
}
