/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;
import java.awt.*;
import java.awt.Color;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.Calendar;

import java.util.GregorianCalendar;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;

import javax.swing.JPanel;

import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Admin
 */
public class edit_cours extends javax.swing.JFrame {
       public String s;
    /**
     * Creates new form Home
     */
       public edit_cours(String id ){
    initComponents();
     System.out.println("--> instituteur choisit a modifier: " + id) ;
       Afficher_donnee( id);
      clock();
    String  id_inst = id;
   
       }
    public edit_cours() {
        initComponents();
        
      
       
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnclock = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        action = new javax.swing.JPanel();
        btnaj = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        labimg = new javax.swing.JLabel();
        btnpath1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtinscri = new javax.swing.JLabel();
        txtpermis = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        prix = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codeM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cap = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.setAlignmentY(0.0F);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        btnclock.setBackground(new java.awt.Color(153, 204, 255));
        btnclock.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnclock.setText("jButton1");
        btnclock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclockActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edit course informations");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(87, 87, 87)
                .addComponent(btnclock, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 70));

        jPanel3.setBackground(new java.awt.Color(220, 246, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        action.setBackground(new java.awt.Color(255, 255, 255));
        action.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0)), "Action :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        btnaj.setBackground(new java.awt.Color(220, 246, 254));
        btnaj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file (2).png"))); // NOI18N
        btnaj.setText("EDIT");
        btnaj.setToolTipText("");
        btnaj.setAutoscrolls(true);
        btnaj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnaj.setContentAreaFilled(false);
        btnaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnaj.setOpaque(true);
        btnaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnajMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnajMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnajMousePressed(evt);
            }
        });
        btnaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionLayout = new javax.swing.GroupLayout(action);
        action.setLayout(actionLayout);
        actionLayout.setHorizontalGroup(
            actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        actionLayout.setVerticalGroup(
            actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnaj, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(action, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 150, 80));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labimg, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labimg, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 220, 230));

        btnpath1.setBackground(new java.awt.Color(0, 0, 102));
        btnpath1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpath1.setForeground(new java.awt.Color(255, 255, 255));
        btnpath1.setText("Browse");
        btnpath1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpath1MouseClicked(evt);
            }
        });
        btnpath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpath1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpath1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 120, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Information of the course:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 0, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtinscri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtinscri.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.add(txtinscri, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 333, 140, 24));

        txtpermis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpermis.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.add(txtpermis, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 303, 140, 24));
        jPanel6.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, -1));

        prix.setMaximumSize(new java.awt.Dimension(9999999, 0));
        prix.setMinimumSize(new java.awt.Dimension(9999999, 0));
        jPanel6.add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, -1));

        jLabel5.setText("code  *:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 21));

        jLabel6.setText("class ability: ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 88, 21));
        jPanel6.add(codeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, -1));

        jLabel8.setText("Description:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 88, 21));

        jLabel10.setText("Price ");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 88, 21));

        cap.setMaximumSize(new java.awt.Dimension(9999999, 0));
        cap.setMinimumSize(new java.awt.Dimension(9999999, 0));
        jPanel6.add(cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, -1));

        jLabel7.setText("Class name:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 21));
        jPanel6.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, -1));

        jLabel1.setFont(new java.awt.Font("Source Code Pro ExtraLight", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("* : Informations cannot be changed");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Source Code Pro ExtraLight", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("* : Informations cannot be changed");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 290, 260));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 950, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection conn=connexionBD.Conexion();
    public void Afficher_donnee(String code){
        String sql="select * from cours where code_mat='"+code+"'";
        
    try {
        PreparedStatement ps1 = conn.prepareStatement(sql);
        ResultSet result = ps1.executeQuery();
           System.out.println("--> SQLException : "+ result ) ;
        if (result.next())
        {
           
            codeM.setText(result.getString("code_mat"));
            nom.setText(result.getString("nom_mat"));
            cap.setValue(result.getInt("cap_mat"));
            desc.setText(result.getString("texte"));
            prix.setValue(result.getInt("prix"));
     
               
            System.out.println("--> erreur1  " ) ;
            

             byte [] img =result.getBytes("image_mat");
             ImageIcon image=new ImageIcon(img);
             Image im=image.getImage();
             Image myimg =im.getScaledInstance(labimg.getWidth(),labimg.getHeight() ,Image.SCALE_SMOOTH);
             ImageIcon imgf=new ImageIcon(myimg);
             labimg.setIcon(imgf);
              System.out.println("--> erreur2  " ) ;
             
        }
            
    } catch (SQLException ex) {
        //Logger.getLogger(instititeur.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("--> SQLException : " + ex) ;
       
    }
        
    }
    public void clock ()
    {
        Calendar cal=new GregorianCalendar();
        int day=cal.get(Calendar.DAY_OF_MONTH);
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        
        int h=cal.get(Calendar.HOUR);
        int m=cal.get(Calendar.MINUTE);
        
        btnclock.setText(  " today is "+day+"/"+month+"/"+year+" : "+h+":"+m);
        
        
    }
   

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnclockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclockActionPerformed

    private void btnajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajActionPerformed
  
         String code_mat= codeM.getText().toString();

        String nom_mat=nom.getText();
        String cap_mat= cap.getValue().toString();
        String texte=desc.getText();
        String price= prix.getValue().toString();
       
        
        try {
             Connection conn = connexionBD.Conexion();
            
            InputStream img = new FileInputStream(new File(s));
            String requete= "UPDATE `cours` SET `nom_mat`='"+nom_mat+"',`cap_mat`='"+cap_mat+"',`texte`='"+texte+"',`prix`='"+price+"',`image_mat`=? WHERE code_mat='"+code_mat+"'";
             System.out.println("requete"+requete);
            
            

           

            PreparedStatement ps = conn.prepareStatement(requete);
            ps.setBlob(1, img);
            
            /*ps.setString(1,num_tlfn);
            ps.setString(2,admail);
            // ps.setString(5, datef);
            ps.setString(3,etat);
            // ps.setString(7,cour_ensg);
            ps.setBlob(4, img);*/
            
           // ps.setInt(5,result.getInt(1));

            //ps.setValue(result.getInt("code_mat"));

            ps.executeUpdate();
            System.out.println(" Course successfully edit");
            JOptionPane.showMessageDialog(null, " Course successfully edit  ");
            
        }catch(SQLException e) {
            System.out.println("--> SQLException : " + e) ;
           
            JOptionPane.showMessageDialog(null, "error ");

        }    catch (FileNotFoundException ex) {
            //Logger.getLogger(ajout_inst.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erreur d'insertion 2");
        }
    }//GEN-LAST:event_btnajActionPerformed

    private void btnajMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMousePressed
        btnaj.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnajMousePressed

    private void btnajMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseExited
        btnaj.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_btnajMouseExited

    private void btnajMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseEntered
        btnaj.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_btnajMouseEntered

    private void btnajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseClicked

    }//GEN-LAST:event_btnajMouseClicked

    private void btnpath1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpath1MouseClicked
        // TODO add your handling code here:
        JFileChooser file =new JFileChooser();
        FileNameExtensionFilter filter =new FileNameExtensionFilter("IMAGE","jpg","png","gif");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);

        if (result==JFileChooser.APPROVE_OPTION){
            File selected=file.getSelectedFile();
            String path = selected.getAbsolutePath();
            ImageIcon image= new ImageIcon(path);
            Image img=image.getImage();
            Image newimage=img.getScaledInstance(labimg.getWidth(),  labimg.getWidth(),Image.SCALE_SMOOTH);
            ImageIcon finalimg = new ImageIcon(newimage);
            labimg.setIcon(finalimg);
            s =path;
            JOptionPane.showMessageDialog(null, "image choisit"+s );
        } else
        {
            if (result==JFileChooser.CANCEL_OPTION)
            JOptionPane.showMessageDialog(null, "choisit une image" );

        }
    }//GEN-LAST:event_btnpath1MouseClicked

    private void btnpath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpath1ActionPerformed

    }//GEN-LAST:event_btnpath1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_cours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_cours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_cours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_cours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_cours().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action;
    private javax.swing.JButton btnaj;
    private javax.swing.JButton btnclock;
    private javax.swing.JButton btnpath1;
    private javax.swing.JSpinner cap;
    private javax.swing.JTextField codeM;
    private javax.swing.JTextField desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labimg;
    private javax.swing.JTextField nom;
    private javax.swing.JSpinner prix;
    private javax.swing.JLabel txtinscri;
    private javax.swing.JLabel txtpermis;
    // End of variables declaration//GEN-END:variables
}
