/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;
import java.awt.*;
import java.awt.Color;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.Calendar;

import java.util.GregorianCalendar;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;

import javax.swing.JPanel;

import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Admin
 */
public class edit_inst extends javax.swing.JFrame {
       public String s;
    /**
     * Creates new form Home
     */
       public edit_inst(String id ){
    initComponents();
     System.out.println("--> instituteur choisit a modifier: " + id) ;
       Afficher_donnee( id);
      clock();
    String  id_inst = id;
   
       }
    public edit_inst() {
        initComponents();
        
      
       
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnclock = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labimg = new javax.swing.JLabel();
        btnpath1 = new javax.swing.JButton();
        action = new javax.swing.JPanel();
        btnaj = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        listeaccee = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dtenaiss = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        num = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nom_pren = new javax.swing.JTextField();
        etat_inst = new javax.swing.JComboBox<>();
        cours = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.setAlignmentY(0.0F);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        btnclock.setBackground(new java.awt.Color(153, 204, 255));
        btnclock.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnclock.setText("jButton1");
        btnclock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclockActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edit teacher informations");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(116, 116, 116)
                .addComponent(btnclock, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnclock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jPanel3.setBackground(new java.awt.Color(220, 246, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Photo instititeur :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labimg, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labimg, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 220, 230));
        jPanel5.getAccessibleContext().setAccessibleName("Teacher picture :");

        btnpath1.setBackground(new java.awt.Color(0, 0, 102));
        btnpath1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpath1.setForeground(new java.awt.Color(255, 255, 255));
        btnpath1.setText("Browse");
        btnpath1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpath1MouseClicked(evt);
            }
        });
        btnpath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpath1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpath1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 120, 40));

        action.setBackground(new java.awt.Color(255, 255, 255));
        action.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0)), "Action :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        btnaj.setBackground(new java.awt.Color(220, 246, 254));
        btnaj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file (2).png"))); // NOI18N
        btnaj.setText("EDIT");
        btnaj.setToolTipText("");
        btnaj.setAutoscrolls(true);
        btnaj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnaj.setContentAreaFilled(false);
        btnaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnaj.setOpaque(true);
        btnaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnajMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnajMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnajMousePressed(evt);
            }
        });
        btnaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionLayout = new javax.swing.GroupLayout(action);
        action.setLayout(actionLayout);
        actionLayout.setHorizontalGroup(
            actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        actionLayout.setVerticalGroup(
            actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnaj, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(action, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 150, 80));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Teacher information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 0, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("ID *:            ");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 88, 18));

        listeaccee.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Name * :");

        dtenaiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtenaissActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero:");

        num.setMaximumSize(new java.awt.Dimension(9999999, 0));
        num.setMinimumSize(new java.awt.Dimension(9999999, 0));

        jLabel7.setText("Mail: ");

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });

        jLabel5.setText("Date of birth *:");

        jLabel23.setText("State :");

        jLabel24.setText("course can teach:");

        nom_pren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_prenActionPerformed(evt);
            }
        });

        etat_inst.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        etat_inst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "single", "married", "divorced", "other" }));

        cours.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        cours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dessin", "musique", "" }));
        cours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listeacceeLayout = new javax.swing.GroupLayout(listeaccee);
        listeaccee.setLayout(listeacceeLayout);
        listeacceeLayout.setHorizontalGroup(
            listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeacceeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(listeacceeLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(77, 77, 77))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(listeacceeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(listeacceeLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(etat_inst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))))
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom_pren, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(listeacceeLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        listeacceeLayout.setVerticalGroup(
            listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeacceeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_pren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(etat_inst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listeacceeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel6.add(listeaccee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 240));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel6.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, -1));

        jLabel26.setText("CIN  *:            ");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 80, 80, 18));

        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });
        jPanel6.add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, -1));

        jLabel1.setFont(new java.awt.Font("Source Code Pro ExtraLight", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("* : Informations cannot be changed");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 290, 370));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection conn=connexionBD.Conexion();
    public void Afficher_donnee(String id_inst){
        String sql="select * from instituteur where id_inst='"+id_inst+"'";
        String sql2="select nom_mat from cours where code_mat=(select code_mat from instituteur where id_inst='"+id_inst+"')";
        System.out.println("--> valeur id  "+id_inst+"     ") ;
    try {
        PreparedStatement ps1 = conn.prepareStatement(sql2);
        ResultSet result2 = ps1.executeQuery();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet result = ps.executeQuery();
           System.out.println("--> SQLException : "+ result ) ;
        if (result.next())
        {
             id.setText(result.getString("id_inst"));
             cin.setText(result.getString("cin_inst"));
            nom_pren.setText(result.getString("name_inst"));
            num.setValue(result.getInt("num_inst"));
            mail.setText(result.getString("mail_inst"));
            dtenaiss.setText(result.getString("dtenaiss_inst"));
             //etat_inst.setItem(result.getString("etat"));
            
             
             result2.next();      
            
            
            String sql3="select nom_mat from cours";
         try {
        cours.removeAllItems();
        cours.addItem (result2.getString("nom_mat"));
        PreparedStatement ps3 = conn.prepareStatement(sql3);
        ResultSet result3 = ps3.executeQuery();
           System.out.println("--> SQLException bien vf : "+ result3 ) ;
            while (result3.next()) {
                cours.addItem(result3.getString(1));
            }
           
       } catch (SQLException ex) {
        //Logger.getLogger(instititeur.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("--> SQLException combobox : " + ex) ;
       
        }    
            System.out.println("--> erreur1  " ) ;
            

             byte [] img =result.getBytes("image");
             ImageIcon image=new ImageIcon(img);
             Image im=image.getImage();
             Image myimg =im.getScaledInstance(labimg.getWidth(),labimg.getHeight() ,Image.SCALE_SMOOTH);
             ImageIcon imgf=new ImageIcon(myimg);
             labimg.setIcon(imgf);
              System.out.println("--> erreur2  " ) ;
             
        }
            
    } catch (SQLException ex) {
        //Logger.getLogger(instititeur.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("--> SQLException : " + ex) ;
       
    }
        
    }
    public void clock ()
    {
        Calendar cal=new GregorianCalendar();
        int day=cal.get(Calendar.DAY_OF_MONTH);
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        
        int h=cal.get(Calendar.HOUR);
        int m=cal.get(Calendar.MINUTE);
        
        btnclock.setText(  " today is "+day+"/"+month+"/"+year+" : "+h+":"+m);
        
        
    }
   

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnclockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclockActionPerformed

    private void btnpath1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpath1MouseClicked
        // TODO add your handling code here:
        JFileChooser file =new JFileChooser();
        FileNameExtensionFilter filter =new FileNameExtensionFilter("IMAGE","jpg","png","gif");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);

        if (result==JFileChooser.APPROVE_OPTION){
            File selected=file.getSelectedFile();
            String path = selected.getAbsolutePath();
            ImageIcon image= new ImageIcon(path);
            Image img=image.getImage();
            Image newimage=img.getScaledInstance(labimg.getWidth(),  labimg.getWidth(),Image.SCALE_SMOOTH);
            ImageIcon finalimg = new ImageIcon(newimage);
            labimg.setIcon(finalimg);
            s =path;
            JOptionPane.showMessageDialog(null, "image choisit"+s );
        } else
        {
            if (result==JFileChooser.CANCEL_OPTION)
            JOptionPane.showMessageDialog(null, "choisit une image" );

        }
    }//GEN-LAST:event_btnpath1MouseClicked

    private void btnpath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpath1ActionPerformed

    }//GEN-LAST:event_btnpath1ActionPerformed

    private void btnajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajActionPerformed
  
         String id_inst= id.getText().toString();
        String num_tlfn= num.getValue().toString();
        String admail=mail.getText();
        String etat =etat_inst.getSelectedItem().toString();
        System.out.println("etat choisit  2"+etat);
        String cour_ensg=cours.getSelectedItem().toString();
        System.out.println("cours choisit  2"+cour_ensg);
      
        
        try {
            String sql1="SELECT code_mat FROM cours WHERE nom_mat='"+cour_ensg+"'";
            Connection conn = connexionBD.Conexion();
            //ps.executeUpdate(requete);                    
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            ResultSet result2 = ps1.executeQuery();
            if (result2.next()){
                int code=result2.getInt("code_mat");
            
            System.out.println("verification    ****");
            System.out.println("requeteaa");
            //Chargement du pilote JDBC pour MYSQL puis creation de la connection
            //DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            // ou bien
            //Connection conn = connexionBD.Conexion();
            //InputStream img = new FileInputStream(new File(s));
System.out.println("requete");
InputStream img = new FileInputStream(new File(s));
            String requete= "UPDATE `instituteur` SET `num_inst`='"+num_tlfn+"',`mail_inst`='"+admail+"',`etat`='"+etat+"',`code_mat`='"+code+"',`image`=? WHERE id_inst='"+id_inst+"'";
             System.out.println("requete"+requete);
            
            

           

            PreparedStatement ps = conn.prepareStatement(requete);
            ps.setBlob(1, img);
            
            /*ps.setString(1,num_tlfn);
            ps.setString(2,admail);
            // ps.setString(5, datef);
            ps.setString(3,etat);
            // ps.setString(7,cour_ensg);
            ps.setBlob(4, img);*/
            
           // ps.setInt(5,result.getInt(1));

            //ps.setValue(result.getInt("code_mat"));

            ps.executeUpdate();
            System.out.println("successfully edit");
            JOptionPane.showMessageDialog(null, " successfully edit  ");
            }
        }catch(SQLException e) {
            System.out.println("--> SQLException : " + e) ;
           
            JOptionPane.showMessageDialog(null, "error ");

        }    catch (FileNotFoundException ex) {
            //Logger.getLogger(ajout_inst.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erreur d'insertion 2");
        }
    }//GEN-LAST:event_btnajActionPerformed

    private void btnajMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMousePressed
        btnaj.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnajMousePressed

    private void btnajMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseExited
        btnaj.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_btnajMouseExited

    private void btnajMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseEntered
        btnaj. setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_btnajMouseEntered

    private void btnajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajMouseClicked

    }//GEN-LAST:event_btnajMouseClicked

    private void dtenaissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtenaissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtenaissActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void nom_prenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_prenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_prenActionPerformed

    private void coursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_inst().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action;
    private javax.swing.JButton btnaj;
    private javax.swing.JButton btnclock;
    private javax.swing.JButton btnpath1;
    private javax.swing.JTextField cin;
    private javax.swing.JComboBox<String> cours;
    private javax.swing.JTextField dtenaiss;
    private javax.swing.JComboBox<String> etat_inst;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labimg;
    private javax.swing.JPanel listeaccee;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nom_pren;
    private javax.swing.JSpinner num;
    // End of variables declaration//GEN-END:variables
}
