
package swing;
import java.awt.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import loginform.login;
import net.proteanit.sql.DbUtils;


public final class liste_inst extends javax.swing.JFrame {
Connection conn=connexionBD.Conexion();

public liste_inst(String inst ,String code ){
    initComponents();
     System.out.println("--> instituteur : " + inst) ;
      System.out.println("--> code : " + code) ;
      
    String  code_mat = code;
    String  nom = inst;
    afficher_cours( code_mat);
    afficher_inst(code_mat, nom);
      clock();
         
      supppay(); 
      
}
    public liste_inst() {
        initComponents();
        
      
      
        
       
        
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnclock = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        liste = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtinscri = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtpermis = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        num = new javax.swing.JSpinner();
        cin = new javax.swing.JSpinner();
        nom_pren1 = new javax.swing.JTextField();
        dtenaiss = new javax.swing.JTextField();
        etat2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        labimg1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtmail = new javax.swing.JLabel();
        txtinscri1 = new javax.swing.JLabel();
        txtetat = new javax.swing.JLabel();
        txtpermis1 = new javax.swing.JLabel();
        nbr = new javax.swing.JSpinner();
        nom = new javax.swing.JTextField();
        code1 = new javax.swing.JSpinner();
        cap = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labimg2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.setAlignmentY(0.0F);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        btnclock.setBackground(new java.awt.Color(153, 204, 255));
        btnclock.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnclock.setText("jButton1");
        btnclock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(btnclock, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnclock, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 50));

        jPanel3.setBackground(new java.awt.Color(220, 246, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Course");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 360, 80));

        liste.setBackground(new java.awt.Color(255, 255, 255));
        liste.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Teacher information  :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        liste.setForeground(new java.awt.Color(0, 0, 204));
        liste.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Name   :");
        liste.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 88, 21));

        jLabel5.setText("Date of birth  :");
        liste.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 25));

        jLabel7.setText("Mail: ");
        liste.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 59, 22));

        txtinscri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtinscri.setForeground(new java.awt.Color(0, 0, 153));
        liste.add(txtinscri, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 333, 140, 24));

        jLabel23.setText("State:");
        liste.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtpermis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpermis.setForeground(new java.awt.Color(0, 0, 153));
        liste.add(txtpermis, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 303, 140, 24));

        jLabel25.setText("CIN   :            ");
        liste.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 88, 18));

        jLabel12.setText("numero  :");
        liste.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 59, 22));
        liste.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, -1));

        num.setMaximumSize(new java.awt.Dimension(9999999, 0));
        num.setMinimumSize(new java.awt.Dimension(9999999, 0));
        liste.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 110, -1));

        cin.setMaximumSize(new java.awt.Dimension(9999999, 0));
        cin.setMinimumSize(new java.awt.Dimension(9999999, 0));
        liste.add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, -1));
        liste.add(nom_pren1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 110, -1));

        dtenaiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtenaissActionPerformed(evt);
            }
        });
        liste.add(dtenaiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, -1));

        etat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etat2ActionPerformed(evt);
            }
        });
        liste.add(etat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, -1));

        jPanel3.add(liste, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 250, 230));

        jPanel7.setBackground(new java.awt.Color(23, 35, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(labimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 210));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, 230));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Information cours :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 0, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Class name :");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 88, 30));

        jLabel8.setText("Nbr register kids ::");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 25));

        jLabel10.setText("Code :");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 88, 18));

        txtmail.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtmail.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 268, 140, 23));

        txtinscri1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtinscri1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.add(txtinscri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 333, 140, 24));

        txtetat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtetat.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.add(txtetat, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 231, 140, 19));

        txtpermis1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpermis1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.add(txtpermis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 303, 140, 24));

        nbr.setMaximumSize(new java.awt.Dimension(9999999, 0));
        nbr.setMinimumSize(new java.awt.Dimension(9999999, 0));
        jPanel6.add(nbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, -1));
        jPanel6.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, -1));

        code1.setMaximumSize(new java.awt.Dimension(9999999, 0));
        code1.setMinimumSize(new java.awt.Dimension(9999999, 0));
        jPanel6.add(code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 110, -1));

        cap.setMaximumSize(new java.awt.Dimension(9999999, 0));
        cap.setMinimumSize(new java.awt.Dimension(9999999, 0));
        jPanel6.add(cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 110, -1));

        jLabel27.setText("Class ability:");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 230, 160));

        jPanel5.setBackground(new java.awt.Color(23, 35, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teacher");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 80));

        jPanel8.setBackground(new java.awt.Color(23, 35, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(labimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 210));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 230, 230));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8-paid-40.png"))); // NOI18N
        jButton2.setText("PAYED FOR THIS MONTH");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 230, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8-money-bag-40.png"))); // NOI18N
        jButton3.setText("PAY FOR THIS MONTH");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 3, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 220, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1090, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     public void supppay()
     {
        Date act= new Date();
        DateFormat df= new SimpleDateFormat("yyyy-MM-dd");
        String Date=df.format(act);
        String d=Date;
          String requete= "DELETE FROM  `payment` WHERE  `date_pay`+30='"+d+"'";      
       
     try {
            PreparedStatement ps = conn.prepareStatement(requete);
            ps.execute();
            jButton3.setVisible(true );
            jButton2.setVisible(false );
           System.out.println("suppression ++");
    } catch (SQLException e) {
        jButton3.setVisible(false );
        jButton2.setVisible(true );
        System.out.println("erreur supp---->"+e);
                  
    }
    }
    public void clock ()
    {
        Calendar cal=new GregorianCalendar();
        int day=cal.get(Calendar.DAY_OF_MONTH);
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        
        int h=cal.get(Calendar.HOUR);
        int m=cal.get(Calendar.MINUTE);
        
       int AM_PM = cal.get(Calendar.AM_PM);  
                    String pa;
                    if(AM_PM==1){
                        pa="PM";
                    }else{
                        pa="AM";
                    }
        
        btnclock.setText(  " today is "+day+"/"+month+"/"+year+" : "+h+":"+m +" "+pa);
        
        
    }
    public void afficher_inst(String code_mat,String  nom){
    
        String sql="select * from instituteur where code_mat='"+code_mat+"'"+"AND name_inst='"+nom+"'";
        
        
    try {
       
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet result = ps.executeQuery();
           System.out.println("--> SQLException : "+ result ) ;
        if (result.next())
        {
            cin.setValue(result.getInt(1));
            nom_pren1.setText(result.getString("name_inst"));
            num.setValue(result.getInt("num_inst"));
            mail.setText(result.getString("mail_inst"));
            dtenaiss.setText(result.getString("dtenaiss_inst"));
             etat2.setText(result.getString("etat"));
             System.out.println("--> SQLException bien  : ") ;
             byte [] img =result.getBytes("image");
             ImageIcon image=new ImageIcon(img);
             Image im=image.getImage();
             Image myimg =im.getScaledInstance(labimg1.getWidth(),labimg1.getHeight() ,Image.SCALE_SMOOTH);
             ImageIcon imgf=new ImageIcon(myimg);
             labimg1.setIcon(imgf);
             
        }
            
    } catch (SQLException ex) {
        //Logger.getLogger(instititeur.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("--> SQLException : " + ex) ;
       
    }
    }
    public void afficher_cours(String code_mat){
        
        String sql="select * from cours where code_mat='"+code_mat+"'";
        
        System.out.println("--> valeur id  "+code_mat+"     ") ;
    try {
       
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet result = ps.executeQuery();
           System.out.println("--> SQLException : "+ result ) ;
       if (result.next())
        {
            code1.setValue(result.getInt("code_mat"));
            nbr.setValue(result.getInt(1));
            nom.setText(result.getString("nom_mat"));
             nbr.setValue(result.getInt("nbrEtdInsc"));
            cap.setValue(result.getInt("cap_mat"));
             System.out.println("--> SQLException bien  : ") ;
             byte [] img =result.getBytes("image_mat");
             ImageIcon image=new ImageIcon(img);
             Image im=image.getImage();
             Image myimg =im.getScaledInstance(labimg2.getWidth(),labimg2.getHeight() ,Image.SCALE_SMOOTH);
             ImageIcon imgf=new ImageIcon(myimg);
             labimg2.setIcon(imgf);
        }
            
    } catch (SQLException ex) {
        //Logger.getLogger(instititeur.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("--> SQLException : " + ex) ;
       
    }
    }
   
 
    
    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
        dispose();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
        dispose();
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
      
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnclockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclockActionPerformed

    private void dtenaissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtenaissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtenaissActionPerformed

    private void etat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etat2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String cin_inst=cin.getValue().toString();
        String  code=code1.getValue().toString();
         payement p=new payement(cin_inst,code);
               
                 p.setVisible(true);
                p.pack();
                p.setLocation(null);
                
         
                p.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                 System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(liste_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(liste_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(liste_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(liste_inst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new liste_inst().setVisible(true);
                 
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclock;
    private javax.swing.JSpinner cap;
    private javax.swing.JSpinner cin;
    private javax.swing.JSpinner code1;
    private javax.swing.JTextField dtenaiss;
    private javax.swing.JTextField etat2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labimg1;
    private javax.swing.JLabel labimg2;
    private javax.swing.JPanel liste;
    private javax.swing.JTextField mail;
    private javax.swing.JSpinner nbr;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nom_pren1;
    private javax.swing.JSpinner num;
    private javax.swing.JLabel txtetat;
    private javax.swing.JLabel txtinscri;
    private javax.swing.JLabel txtinscri1;
    private javax.swing.JLabel txtmail;
    private javax.swing.JLabel txtpermis;
    private javax.swing.JLabel txtpermis1;
    // End of variables declaration//GEN-END:variables
}
